Anna design feedback
DecentralCardGame/frontend pull request #290
Opened 2024-03-23 06:37 UTC by patrickwieth

2024-03-27 13:42 UTC, lxgr-linux requested changes

2024-03-27 13:42 UTC, lxgr-linux commented on src/def-composables/useLogin.ts
> +      console.log("signUpRequired?", required)
Bitte nicht

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +        <div class="uppercase font-bold pt-12">
bitte `<p>` tag benutzen

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +          <div class="pl-[0rem] pt-5 pb-4 h-[26.5rem]">
`pl-...` vllt weg

2024-03-27 13:42 UTC, lxgr-linux commented on src/components/modals/GalleryModal.vue
> +  console.log("lastinputevent", event)
Console log s weg

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +                  maxLength="250"
Gabs nicht schon probleme mit sehr langem flavourtext?

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +          <div class="pl-[0rem] pt-5 pb-4 h-[26.5rem]">
same

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +          <div class="pl-[0rem] pt-5 pb-4 h-[26.5rem]">
same

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +            <div class="pl-10 pr-[4.0rem] py-5 justify-center">
4.0 nicht 4?

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +          <div class="pl-[0rem] pt-5 pb-4 h-[26.5rem]">
same

2024-03-27 13:42 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +        "open",
Diesen ganzen progressbar spaß kann man doch mit EINEM enum lösen, bitte nicht liste von werten bei dem genau immer einer active ist

2024-03-27 14:52 UTC, lxgr-linux commented on src/def-composables/useLogin.ts
> +      console.log("signUpRequired?", required)
mach lieber ganz raus

2024-03-27 14:59 UTC, patrickwieth commented on src/views/CardCreatorPage.vue
> +                  maxLength="250"
nö, du meinst wahrscheinlich kartentitel oder etwas was auch angezeigt wird auf der karte

2024-03-27 15:00 UTC, patrickwieth commented on src/views/CardCreatorPage.vue
> +            <div class="pl-10 pr-[4.0rem] py-5 justify-center">
ja

2024-03-27 15:01 UTC, patrickwieth commented on src/views/CardCreatorPage.vue
> +        "open",
es gibt 3 states

2024-03-28 11:36 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +                  maxLength="250"
Irgendwer hat sich doch meune mal beschwehrt, dass die flovoutexts im cardview zu lang sind

2024-03-28 11:37 UTC, lxgr-linux commented on src/views/CardCreatorPage.vue
> +        "open",
3 states?
es gibt doch immer nur einen view, das activ ist, oder?

2024-03-28 11:46 UTC, lxgr-linux approved these changes
LGTM

2024-03-31 17:49 UTC, merged